services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    depends_on:
      - db
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

#  web:
#    build: ./frontend
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./frontend:/frontend

volumes:
  db: